RecipePrintouts/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ProjectFolder.views.home', name='home'),
    # url(r'^ProjectFolder/', include('ProjectFolder.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^preview/', include('template_previewer.urls')),
    #url(r'^templatepreview/', include('previewer.urls')),
    
    url(r'^recipeprintoutsapp/', include('recipeprintoutsapp.urls',namespace="recipeprintoutsapp")),
    url(r'^admin/', include(admin.site.urls)),
)

recipeprintoutsapp/urls.py
#This is the enersectapp urls file

from django.conf.urls import patterns, url

from recipeprintoutsapp import views

urlpatterns = patterns('',

    # Maintenance Screen
    # ex: recipeprintoutsapp/maintenance_screen
    #url(r'^maintenance_screen/$', views.maintenance_screen, name='maintenance_screen'),

    #Log In View when not authentificated
    #return redirect('/login/' % request.path)
    #ex: /recipeprintoutsapp/login/
    url(r'^login/$', views.app_login, name='app_login'),
        
    # Note: To access to admin panel, the url is simply /admin
    # Admin already has an authentification mode built in.

    # Main (app_index). Shows the four available modes. Can't access them at the moment
    # ex: /recipeprintoutsapp/
    url(r'^$', views.app_index, name='app_index'),   
    
        # Ingredient Nutritional Showcase (Ingredient Search)
        # Shows you an input in which you can search the ingredient you want to look up.
        # (For example, "raw turtle"). When accepted, it will show you the nutritional profile of raw turtle.
        # ex: /subtool/ingredient_search/10021&20030&
        # Note: /subtool/ingredient_search/none when no ingredients are selected
        url(r'^subtool/ingredient_search/(?P<ingredients_string>\w+)/$', views.ingredient_search, name='ingredient_search'),

)

recipeprintoutsapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

#Table to organise the different possible views/interfaces (in case there are different tools)

class UserInterfaceType(models.Model):
    name = models.CharField(max_length=255,default='')
    redirection_url = models.CharField(max_length=255,default='')
    def __unicode__(self):
        return self.name





# Sources of Data File (file name = DATA_SRC). This file (Table 15) provides a citation 
# to the DataSrc_ID in the Sources of Data Link file. 

class DataSrc(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    datasrc_id = models.TextField(unique=True, db_column='DataSrc_ID', blank=True) # Field name made lowercase.
    authors = models.TextField(db_column='Authors', blank=True) # Field name made lowercase.
    title = models.TextField(db_column='Title', blank=True) # Field name made lowercase.
    year = models.TextField(db_column='Year', blank=True) # Field name made lowercase.
    journal = models.TextField(db_column='Journal', blank=True) # Field name made lowercase.
    vol_city = models.TextField(db_column='Vol_City', blank=True) # Field name made lowercase.
    issue_state = models.TextField(db_column='Issue_State', blank=True) # Field name made lowercase.
    start_page = models.TextField(db_column='Start_Page', blank=True) # Field name made lowercase.
    end_page = models.TextField(db_column='End_Page', blank=True) # Field name made lowercase.
    
    class Meta:
        db_table = 'data_src'
    def __unicode__(self):
        return self.datasrc_id

# Sources of Data Link File (file name = DATSRCLN). This file (Table 14) is used to link 
# the Nutrient Data file with the Sources of Data table. It is needed to resolve the many-to-many
 # relationship between the two tables.
        
class Datsrcln(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    ndb_no = models.TextField(db_column='NDB_No', blank=True) # Field name made lowercase.
    nutr_no = models.TextField(db_column='Nutr_No', blank=True) # Field name made lowercase.
    datasrc_id = models.TextField(db_column='DataSrc_ID', blank=True) # Field name made lowercase.
    
    DataSrc_Link = models.ForeignKey('DataSrc', blank=True,null =True)
    
    class Meta:
        db_table = 'datsrcln'
    def __unicode__(self):
        return self.datasrc_id
        
# Data Derivation Code Description File (file name = DERIV_CD). This file (Table 11) 
# provides information on how the nutrient values were determined. The file contains the 
# derivation codes and their descriptions.         
        
        
class DerivCd(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    deriv_cd = models.TextField(unique=True, db_column='Deriv_Cd', blank=True) # Field name made lowercase.
    deriv_desc = models.TextField(db_column='Deriv_Desc', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'deriv_cd'
    def __unicode__(self):
        return self.deriv_desc
        
#Food Group Description File (file name = FD_GROUP). This file (Table 5) is a 
# support file to the Food Description file and contains a list of food groups used in SR26 
# and their descriptions.         
        
class FdGroup(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    fdgrp_cd = models.TextField(unique=True, db_column='FdGrp_Cd', blank=True) # Field name made lowercase.
    fdgrp_desc = models.TextField(db_column='FdGrp_Desc', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'fd_group'
    def __unicode__(self):
        return self.fdgrp_desc
        
#Food Description File (file name = FOOD_DES). This file (Table 4) contains long and 
# short descriptions and food group designators for 8,463 food items, along with common 
# names, manufacturer name, scientific name, percentage and description of refuse, and 
# factors used for calculating protein and kilocalories, if applicable. Items used in the 
# FNDDS are also identified by value of "Y" in the Survey field.     
        
class FoodDes(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    ndb_no = models.TextField(unique=True, db_column='NDB_No', blank=True) # Field name made lowercase.
    fdgrp_cd = models.TextField(db_column='FdGrp_Cd', blank=True) # Field name made lowercase.
    long_desc = models.TextField(db_column='Long_Desc', blank=True) # Field name made lowercase.
    shrt_desc = models.TextField(db_column='Shrt_Desc', blank=True) # Field name made lowercase.
    comname = models.TextField(db_column='ComName', blank=True) # Field name made lowercase.
    manufacname = models.TextField(db_column='ManufacName', blank=True) # Field name made lowercase.
    survey = models.TextField(db_column='Survey', blank=True) # Field name made lowercase.
    ref_desc = models.TextField(db_column='Ref_desc', blank=True) # Field name made lowercase.
    refuse = models.TextField(db_column='Refuse', blank=True) # Field name made lowercase.
    sciname = models.TextField(db_column='SciName', blank=True) # Field name made lowercase.
    n_factor = models.TextField(db_column='N_Factor', blank=True) # Field name made lowercase.
    pro_factor = models.TextField(db_column='Pro_Factor', blank=True) # Field name made lowercase.
    fat_factor = models.TextField(db_column='Fat_Factor', blank=True) # Field name made lowercase.
    cho_factor = models.TextField(db_column='CHO_Factor', blank=True) # Field name made lowercase.
    
    FdGroup_Link = models.ForeignKey('FdGroup', blank=True,null =True)
    Footnote_Link = models.ForeignKey('Footnote', blank=True,null =True)
    NutData_Link = models.ManyToManyField('NutData', blank=True,null =True)
    Weight_Link = models.ForeignKey('Weight', blank=True,null =True)
    Langual_Link = models.ManyToManyField('Langual', blank=True,null =True)
    
    class Meta:
        db_table = 'food_des'
    def __unicode__(self):
        return self.long_desc
        
# Footnote File (file name = FOOTNOTE). This file (Table 13) contains additional 
# information about the food item, household weight, and nutrient value.         
        
class Footnote(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    ndb_no = models.TextField(db_column='NDB_No', blank=True) # Field name made lowercase.
    footnt_no = models.TextField(db_column='Footnt_No', blank=True) # Field name made lowercase.
    footnt_typ = models.TextField(db_column='Footnt_Typ', blank=True) # Field name made lowercase.
    nutr_no = models.TextField(db_column='Nutr_No', blank=True) # Field name made lowercase.
    footnt_txt = models.TextField(db_column='Footnt_Txt', blank=True) # Field name made lowercase.
    
    NutData_Link = models.ManyToManyField('NutData', blank=True,null =True)
    
    class Meta:
        db_table = 'footnote'
    def __unicode__(self):
        return self.footnt_txt
        
        
# LanguaL Factors Description File (File name = LANGDESC). This file (Table 7) is a 
# support file to the LanguaL Factor file and contains the descriptions for only those 
# factors used in coding the selected food items codes in this release of SR.         
        
class Langdesc(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    factor_code = models.TextField(db_column='Factor_Code', blank=True) # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'langdesc'
    def __unicode__(self):
        return self.description
        
# LanguaL Factor File (File name = LANGUAL). This file (Table 6) is a support file to the 
# Food Description file and contains the factors from the LanguaL Thesaurus used to 
# code a particular food.       
        
class Langual(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    ndb_no = models.TextField(db_column='NDB_No', blank=True) # Field name made lowercase.
    factor_code = models.TextField(db_column='Factor_Code', blank=True) # Field name made lowercase.
    
    Langdesc_Link = models.ForeignKey('Langdesc', blank=True,null =True)
    
    class Meta:
        db_table = 'langual'
    def __unicode__(self):
        return self.factor_code
        
# Nutrient Data File (file name = NUT_DATA). This file (Table 8) contains the nutrient 
# values and information about the values, including expanded statistical information.       
        
class NutData(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    ndb_no = models.TextField(db_column='NDB_No', blank=True) # Field name made lowercase.
    nutr_no = models.TextField(db_column='Nutr_No', blank=True) # Field name made lowercase.
    nutr_val = models.TextField(db_column='Nutr_Val', blank=True) # Field name made lowercase.
    num_data_pts = models.TextField(db_column='Num_Data_Pts', blank=True) # Field name made lowercase.
    std_error = models.TextField(db_column='Std_Error', blank=True) # Field name made lowercase.
    src_cd = models.TextField(db_column='Src_Cd', blank=True) # Field name made lowercase.
    deriv_cd = models.TextField(db_column='Deriv_Cd', blank=True) # Field name made lowercase.
    ref_ndb_no = models.TextField(db_column='Ref_NDB_No', blank=True) # Field name made lowercase.
    add_nutr_mark = models.TextField(db_column='Add_Nutr_Mark', blank=True) # Field name made lowercase.
    num_studies = models.TextField(db_column='Num_Studies', blank=True) # Field name made lowercase.

recipeprintoutsapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate

from django.shortcuts import get_object_or_404, render, redirect,render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.template import RequestContext
from django.views import generic
from django.utils import timezone
from datetime import timedelta
import datetime
from django.db import transaction
from django.db import connection
import re
import json,csv
from django.core import serializers
import random
from pyPdf import PdfFileWriter, PdfFileReader
from urllib2 import Request, urlopen
from StringIO import StringIO
from django.db.models import Count

from recipeprintoutsapp.viewsfunctions import (app_index_module,app_login_module,ingredient_search_module)

from recipeprintoutsapp.models import *

def maintenance_screen(request):
  
    return render(request,'recipeprintoutsapp/maintenance_screen.html',context)

def app_login(request):
  
    return app_login_module.app_login(request)

def app_index(request):
    
    return app_index_module.app_index(request)
    
def ingredient_search(request,ingredients_string = None):
    
    return ingredient_search_module.ingredient_search(request,ingredients_string)

recipeprintoutsapp/templates/recipeprintoutsapp/app_index.html
{% load i18n %}

{% block page_title %}
<head>
<title>RecipePrinouts Apps Main Menu</title>
</head>
{% endblock page_title %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/css/eggplant/jquery-ui-1.10.3.custom.css' %}" />
<script type="text/javascript" src="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js' %}" ></script>
<script type="text/javascript" src="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js' %}" ></script>

<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/user_panel_module.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/app_index.css' %}" /> 
<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/site_basic_style_template.css' %}" />


<script>
    
    $(document).ready(function(){
        
        createUserPanel();
        
        $( "#tools-panel" ).dialog({
                  
                  height: $('body').height()-30,
                  
                  modal: false,
                  autoOpen:true,
                  closeOnEscape: false,
                  resizable:true,
                  
                  
        });
                
        $( "#toolspanelmenu" ).menu({ position: { my: "right bottom", at: "right bottom" },
                    select: function( event, ui ) {
                        
                    } 
        });    


        function createUserPanel(){
        
            $( "#user-panel" ).dialog({
                  
                  height: $('#userpanel_container').height(),
                  width: $('#userpanel_container').width(),
                  modal: false,
                  autoOpen:true,
                  closeOnEscape: false,
                  resizable:true,
                  position: {
                    my: "left bottom", at: "left bottom", of: $('#userpanel_container')
                    }
                  
                });
                
                $( "#userpanelmenu" ).menu({ position: { my: "right bottom", at: "right bottom" },
                    select: function( event, ui ) {
                        
                    } 
                });
        }
    
    });
    

</script>

<body>

    
    <div id="toolspanel_container">
            <div id="tools-panel" title="Tools Available">
                <!--<p class="validateTips_ToolsAvailable">Comment paragraph</p>-->
                <ul class="menuclass" id="toolspanelmenu">
                    {% for userinterfacetype in uitype_list %}
                        <li><a href="{{userinterfacetype.redirection_url}}">{{userinterfacetype.id}}.{{ userinterfacetype.name }}</a></li>
                        <li>--</li>
                    {% endfor %}
                        <li><a href="{% url 'admin:index' %}">Admin App</a></li>
                </ul>
            </div>
    </div>
    
    <div id="userpanel_container">
            <div id="user-panel" title="{{the_user.username}}">
                
                <ul class="menuclass" id="userpanelmenu">
                    <li><a id="logout_link" href="{% url 'recipeprintoutsapp:app_login' %}">Change User</a></li>
                    
                </ul>
            </div>
    </div>
    
</body>

recipeprintoutsapp/templates/recipeprintoutsapp/app_login.html
{% load i18n admin_static %}

{% block config_libs %} 

<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/css/eggplant/jquery-ui-1.10.3.custom.css' %}" />
<script type="text/javascript" src="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js' %}" ></script>
<script type="text/javascript" src="{% static 'recipeprintoutsapp/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js' %}" ></script>


{% endblock config_libs %}

{% block special_libs %} 
<link rel="stylesheet" type="text/css" href="{% static 'recipeprintoutsapp/app_login.css' %}" />

{% endblock special_libs %}

{% block javascript %} 

<script>

    $(document).ready(function () {
    
        $( "#login" ).dialog({
          autoOpen: true,
          height: 300,
          width: 350,
          modal: true,
          closeOnEscape: false,
          resizable: false,
          buttons: {
            "Login": function() {
                $('#LoginForm').submit();
            }
          }
          
        });
    
    
    });

</script>

{% endblock javascript %}

{% block content %}
    <div id="login" title="Log In">
        <form id="LoginForm" name="LoginForm" action="{% url 'recipeprintoutsapp:app_login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
              
          <fieldset>
            <label for="username">Username</label>
            <input type="text" name="username" id="username"  class="text ui-widget-content ui-corner-all" />
            <label for="password">Password</label>
            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
          </fieldset>

        </form>
    </div>
{% endblock %}